pipeline {
//        agent {
//        docker {
//            image 'maven:3-alpine'
//            args '-v /root/.m2:/root/.m2'
//        }
//    }
          agent { none }
    options {
        skipStagesAfterUnstable()
    }
    stages {
//        agent {
//          docker {
//            image 'maven:3-alpine'
//            args '-v /root/.m2:/root/.m2'
//          }
//        }
        stage('Build') {
            steps {
                sh 'mvn -v'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dmaven.test.failure.ignore=true'
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('build image') {
          agent { 
            docker {
              image 'registry.joszh.com/docker:19'
            }
          }  
          steps {
                 sh 'docker version'                        

          }
        }
    }

}
