pipeline {
        agent { none }
    //agent { label 'master' }
    options {
        skipStagesAfterUnstable()
    }
    node ('maven') {
        stage('Build') {
            steps {
                sh 'mvn -v'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                //sh 'docker version'
                sh 'mvn -v'
                sh 'mvn test -Dmaven.test.failure.ignore=true'
            }
            post {
                success {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'mvn -v'
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('build image') {
          agent { node { label 'master'} }
          steps {
                 sh 'mvn -v'
                 sh 'docker version'                        

          }
        }
    }

}
